version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: shorter-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
      MONGO_INITDB_DATABASE: shorter
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shorter
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 80
      MONGODB_URI: mongodb://admin:secretpassword@mongodb:27017/shorter?authSource=admin
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge